trigger:
  - main

pool:
  name: 'Default'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration Release --framework net8.0'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Build'
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishPipelineArtifact@1
    displayName: 'Upload Artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'abdo_lab4_artifact'
